// Mocks generated by Mockito 5.4.4 from annotations
// in blog_app/test/lib/features/posts/data/repositories/posts_repositories_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blog_app/core/network/network_info.dart' as _i6;
import 'package:blog_app/features/posts/data/datasources/posts_remote_data_source.dart'
    as _i3;
import 'package:blog_app/features/posts/data/models/post_model.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUnit_0 extends _i1.SmartFake implements _i2.Unit {
  _FakeUnit_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BasePostRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBasePostRemoteDataSource extends _i1.Mock
    implements _i3.BasePostRemoteDataSource {
  MockBasePostRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PostModel>> getAllPosts() => (super.noSuchMethod(
        Invocation.method(
          #getAllPosts,
          [],
        ),
        returnValue: _i4.Future<List<_i5.PostModel>>.value(<_i5.PostModel>[]),
      ) as _i4.Future<List<_i5.PostModel>>);

  @override
  _i4.Future<_i2.Unit> updatePost(_i5.PostModel? postModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePost,
          [postModel],
        ),
        returnValue: _i4.Future<_i2.Unit>.value(_FakeUnit_0(
          this,
          Invocation.method(
            #updatePost,
            [postModel],
          ),
        )),
      ) as _i4.Future<_i2.Unit>);

  @override
  _i4.Future<_i2.Unit> createPost(_i5.PostModel? postModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [postModel],
        ),
        returnValue: _i4.Future<_i2.Unit>.value(_FakeUnit_0(
          this,
          Invocation.method(
            #createPost,
            [postModel],
          ),
        )),
      ) as _i4.Future<_i2.Unit>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
